/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/temporary-absence-occurrences/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getTapOccurrence']
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    put: operations['applyActions']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-authorisations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getTapAuthorisation']
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    put: operations['applyActions_1']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-movements/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    put: operations['syncTemporaryAbsenceMovement']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-authorisations/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    put: operations['syncTemporaryAbsenceAuthorisation']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-authorisations/{authorisationId}/occurrences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    put: operations['syncTemporaryAbsenceOccurrence']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/resync/temporary-absences/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    put: operations['mergeTemporaryAbsences']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/move/temporary-absences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    put: operations['moveTemporaryAbsences']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-authorisations/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    post: operations['createTapAuthorisation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-authorisations/{id}/occurrences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    post: operations['createOccurrence']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/temporary-absence-occurrences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    post: operations['searchTapOccurrences']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/temporary-absence-authorisations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    post: operations['searchTapAuthorisations']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/people/{personIdentifier}/temporary-absence-occurrences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    post: operations['searchPersonTap']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-occurrences/{id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getTapOccurrenceHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-movements/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    get: operations['getTapMovement']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-movements/{id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    get: operations['getTapMovementHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/temporary-absence-authorisations/{id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getTapAuthorisationHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-occurrences/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    get: operations['findTapOccurrenceById']
    put?: never
    post?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    delete: operations['deleteTapOccurrenceById']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-movements/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    get: operations['findTapMovementById']
    put?: never
    post?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    delete: operations['deleteTapMovementById']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync/temporary-absence-authorisations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    get: operations['findTapAuthorisationById']
    put?: never
    post?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    delete: operations['deleteTapAuthorisationById']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/external-movements/schedules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS__RW
     */
    get: operations['externalMovementSchedules']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reference-data/{domain}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getDomain']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconciliation/{personIdentifier}/temporary-absences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    get: operations['countTemporaryAbsences']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reconciliation-detail/{personIdentifier}/temporary-absences': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__SYNC__RW
     */
    get: operations['getTemporaryAbsences']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonIdentifier}/external-movements/overview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    get: operations['getPrisonOverview']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/absence-categorisation/{domain}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getAbsenceCategorisationDomain']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/absence-categorisation/{domain}/{code}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO
     *     * ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW
     */
    get: operations['getAbsenceCategorisationOptions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/absence-categorisation/filters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI
     */
    get: operations['getAbsenceCategorisationFilters']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CancelOccurrence: {
      type: 'CancelOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    ChangeOccurrenceAccompaniment: {
      type: 'ChangeOccurrenceAccompaniment'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      accompaniedByCode: string
      reason?: string | null
    })
    ChangeOccurrenceComments: {
      type: 'ChangeOccurrenceComments'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      comments?: string | null
      reason?: string | null
    })
    ChangeOccurrenceContactInformation: {
      type: 'ChangeOccurrenceContactInformation'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      information: string
      reason?: string | null
    })
    ChangeOccurrenceLocation: {
      type: 'ChangeOccurrenceLocation'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      location: components['schemas']['Location']
      reason?: string | null
    })
    ChangeOccurrenceTransport: {
      type: 'ChangeOccurrenceTransport'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      transportCode: string
      reason?: string | null
    })
    CommenceOccurrence: {
      type: 'CommenceOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    CompleteOccurrence: {
      type: 'CompleteOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    DenyOccurrence: {
      type: 'DenyOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    ExpireOccurrence: {
      type: 'ExpireOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    Location: {
      description?: string | null
      address?: string | null
      postcode?: string | null
      /** Format: int64 */
      uprn?: number | null
    }
    MarkOccurrenceOverdue: {
      type: 'MarkOccurrenceOverdue'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    OccurrenceAction: {
      reason?: string
      type: string
    }
    PauseOccurrence: {
      type: 'PauseOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    RecategoriseOccurrence: {
      type: 'RecategoriseOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCategoryCode?: string | null
      absenceReasonCode?: string | null
      reason?: string | null
    })
    RescheduleOccurrence: {
      type: 'RescheduleOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      /** Format: date-time */
      start?: string | null
      /** Format: date-time */
      end?: string | null
      reason?: string | null
    })
    ResumeOccurrence: {
      type: 'ResumeOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    ScheduleOccurrence: {
      type: 'ScheduleOccurrence'
    } & (Omit<components['schemas']['OccurrenceAction'], 'type'> & {
      reason?: string | null
    })
    AuditHistory: {
      content: components['schemas']['AuditedAction'][]
    }
    AuditedAction: {
      user: components['schemas']['User']
      /** Format: date-time */
      occurredAt: string
      domainEvents: string[]
      reason?: string | null
      changes: components['schemas']['Change'][]
    }
    Change: {
      propertyName: string
      previous?: null | string
      change?: null | string
    }
    User: {
      username: string
      name: string
    }
    ApproveAuthorisation: {
      type: 'ApproveAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    AuthorisationAction: {
      reason?: string
      type: string
    }
    CancelAuthorisation: {
      type: 'CancelAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    ChangeAuthorisationAccompaniment: {
      type: 'ChangeAuthorisationAccompaniment'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      accompaniedByCode: string
      reason?: string | null
    })
    ChangeAuthorisationComments: {
      type: 'ChangeAuthorisationComments'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      comments?: string | null
      reason?: string | null
    })
    ChangeAuthorisationDateRange: {
      type: 'ChangeAuthorisationDateRange'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      reason?: string | null
    })
    ChangeAuthorisationLocation: {
      type: 'ChangeAuthorisationLocation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      location: components['schemas']['Location']
      reason?: string | null
    })
    ChangeAuthorisationLocations: {
      type: 'ChangeAuthorisationLocations'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      locations: components['schemas']['Location'][]
      reason?: string | null
    })
    ChangeAuthorisationTransport: {
      type: 'ChangeAuthorisationTransport'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      transportCode: string
      reason?: string | null
    })
    ChangePrisonPerson: {
      type: 'ChangePrisonPerson'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      personIdentifier: string
      prisonCode: string
      reason?: string | null
    })
    ClearAuthorisationSchedule: {
      type: 'ClearAuthorisationSchedule'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    DeferAuthorisation: {
      type: 'DeferAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    DenyAuthorisation: {
      type: 'DenyAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    ExpireAuthorisation: {
      type: 'ExpireAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    PauseAuthorisation: {
      type: 'PauseAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    RecategoriseAuthorisation: {
      type: 'RecategoriseAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCategoryCode?: string | null
      absenceReasonCode?: string | null
      reason?: string | null
    })
    ResumeAuthorisation: {
      type: 'ResumeAuthorisation'
    } & (Omit<components['schemas']['AuthorisationAction'], 'type'> & {
      reason?: string | null
    })
    SyncAtAndBy: {
      /** Format: date-time */
      at: string
      by: string
    }
    SyncWriteTapMovement: {
      /** Format: uuid */
      id?: string | null
      /** Format: uuid */
      occurrenceId?: string | null
      /** Format: date-time */
      occurredAt: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      prisonCode: string
      absenceReasonCode: string
      location: components['schemas']['Location']
      accompaniedByCode: string
      accompaniedByComments?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      legacyId: string
    }
    SyncResponse: {
      /** Format: uuid */
      id: string
    }
    SyncWriteTapAuthorisation: {
      /** Format: uuid */
      id?: string | null
      prisonCode: string
      statusCode: string
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      startTime: string
      endTime: string
      location?: components['schemas']['Location'] | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      /** Format: int64 */
      legacyId: number
    }
    SyncWriteTapOccurrence: {
      /** Format: uuid */
      id?: string | null
      isCancelled: boolean
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      contactInformation?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      /** Format: int64 */
      legacyId: number
    }
    MigrateTapAuthorisation: {
      prisonCode: string
      statusCode: string
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      startTime: string
      endTime: string
      location?: components['schemas']['Location'] | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      /** Format: int64 */
      legacyId: number
      /** Format: uuid */
      id?: string | null
      occurrences: components['schemas']['MigrateTapOccurrence'][]
    }
    MigrateTapMovement: {
      /** Format: date-time */
      occurredAt: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      prisonCode: string
      absenceReasonCode: string
      location: components['schemas']['Location']
      accompaniedByCode: string
      accompaniedByComments?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      legacyId: string
      /** Format: uuid */
      id?: string | null
    }
    MigrateTapOccurrence: {
      isCancelled: boolean
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      contactInformation?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      /** Format: int64 */
      legacyId: number
      /** Format: uuid */
      id?: string | null
      movements: components['schemas']['MigrateTapMovement'][]
    }
    MigrateTapRequest: {
      temporaryAbsences: components['schemas']['MigrateTapAuthorisation'][]
      unscheduledMovements: components['schemas']['MigrateTapMovement'][]
    }
    MigrateTapResponse: {
      temporaryAbsences: components['schemas']['MigratedAuthorisation'][]
      unscheduledMovements: components['schemas']['MigratedMovement'][]
    }
    MigratedAuthorisation: {
      /** Format: int64 */
      legacyId: number
      /** Format: uuid */
      id: string
      occurrences: components['schemas']['MigratedOccurrence'][]
    }
    MigratedMovement: {
      legacyId: string
      /** Format: uuid */
      id: string
    }
    MigratedOccurrence: {
      /** Format: int64 */
      legacyId: number
      /** Format: uuid */
      id: string
      movements: components['schemas']['MigratedMovement'][]
    }
    MoveTemporaryAbsencesRequest: {
      fromPersonIdentifier: string
      toPersonIdentifier: string
      authorisationIds: string[]
      unscheduledMovementIds: string[]
    }
    /** @description AuthorisationSchedule */
    AuthorisationSchedule: {
      type: components['schemas']['AuthorisationScheduleType']
    }
    /** @enum {string} */
    AuthorisationScheduleType: 'SINGLE' | 'FREEFORM' | 'WEEKLY' | 'BIWEEKLY' | 'SHIFT'
    BiweeklyPattern: {
      weekA: components['schemas']['WeekDayPattern'][]
      weekB: components['schemas']['WeekDayPattern'][]
    }
    BiweeklySchedule: Omit<WithRequired<components['schemas']['AuthorisationSchedule'], 'type'>, 'type'> & {
      biweeklyPattern: components['schemas']['BiweeklyPattern']
      /** Format: int32 */
      absencesPerDay?: number | null
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'BIWEEKLY'
    }
    CreateTapAuthorisationRequest: {
      absenceTypeCode: string
      absenceSubTypeCode?: string | null
      absenceReasonCategoryCode?: string | null
      absenceReasonCode?: string | null
      occurrences: components['schemas']['OccurrenceRequest'][]
      /** @enum {string} */
      statusCode: 'PENDING' | 'APPROVED' | 'PAUSED' | 'CANCELLED' | 'DENIED' | 'EXPIRED'
      accompaniedByCode: string
      transportCode: string
      comments?: string | null
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      contactInformation?: string | null
      schedule?:
        | components['schemas']['BiweeklySchedule']
        | components['schemas']['FreeFormSchedule']
        | components['schemas']['ShiftSchedule']
        | components['schemas']['SingleSchedule']
        | components['schemas']['WeeklySchedule']
    }
    DayShiftPattern: Omit<WithRequired<components['schemas']['ShiftPattern'], 'count' | 'type'>, 'type'> & {
      startTime: string
      returnTime: string
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'DAY'
    }
    FreeFormSchedule: Omit<WithRequired<components['schemas']['AuthorisationSchedule'], 'type'>, 'type'> & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'FREEFORM'
    }
    NightShiftPattern: Omit<WithRequired<components['schemas']['ShiftPattern'], 'count' | 'type'>, 'type'> & {
      startTime: string
      returnTime: string
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'NIGHT'
    }
    OccurrenceRequest: {
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
    }
    RestShiftPattern: Omit<WithRequired<components['schemas']['ShiftPattern'], 'count' | 'type'>, 'type'> & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'REST'
    }
    /** @description ShiftPattern */
    ShiftPattern: {
      /** Format: int32 */
      count: number
      type: components['schemas']['ShiftPatternType']
    }
    /** @enum {string} */
    ShiftPatternType: 'DAY' | 'NIGHT' | 'REST'
    ShiftSchedule: Omit<WithRequired<components['schemas']['AuthorisationSchedule'], 'type'>, 'type'> & {
      shiftPattern: (
        | components['schemas']['DayShiftPattern']
        | components['schemas']['NightShiftPattern']
        | components['schemas']['RestShiftPattern']
      )[]
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'SHIFT'
    }
    SingleSchedule: Omit<WithRequired<components['schemas']['AuthorisationSchedule'], 'type'>, 'type'> & {
      startTime: string
      returnTime: string
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'SINGLE'
    }
    WeekDayPattern: {
      /** Format: int32 */
      day: number
      overnight: boolean
      startTime: string
      returnTime: string
    }
    WeeklySchedule: Omit<WithRequired<components['schemas']['AuthorisationSchedule'], 'type'>, 'type'> & {
      weeklyPattern: components['schemas']['WeekDayPattern'][]
      /** Format: int32 */
      absencesPerDay?: number | null
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'WEEKLY'
    }
    ReferenceId: {
      /** Format: uuid */
      id: string
    }
    CreateOccurrenceRequest: {
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      comments?: string | null
    }
    AbsenceCategorisationFilter: {
      /** @enum {string} */
      domainCode:
        | 'ABSENCE_TYPE'
        | 'ABSENCE_SUB_TYPE'
        | 'ABSENCE_REASON_CATEGORY'
        | 'ABSENCE_REASON'
        | 'ACCOMPANIED_BY'
        | 'TRANSPORT'
        | 'TAP_AUTHORISATION_STATUS'
        | 'TAP_OCCURRENCE_STATUS'
      codes: string[]
    }
    TapOccurrenceSearchRequest: {
      prisonCode: string
      /** Format: date */
      start?: string | null
      /** Format: date */
      end?: string | null
      status: (
        | 'PENDING'
        | 'SCHEDULED'
        | 'PAUSED'
        | 'IN_PROGRESS'
        | 'COMPLETED'
        | 'OVERDUE'
        | 'EXPIRED'
        | 'CANCELLED'
        | 'DENIED'
      )[]
      absenceCategorisation?: components['schemas']['AbsenceCategorisationFilter'] | null
      query?: string | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    CodedDescription: {
      code: string
      description: string
      hintText?: string | null
    }
    PageMetadata: {
      /** Format: int64 */
      totalElements: number
    }
    Person: {
      personIdentifier: string
      firstName: string
      lastName: string
      prisonCode?: string | null
      cellLocation?: string | null
    }
    TapOccurrenceAuthorisation: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      repeat: boolean
      schedule?: null &
        (
          | components['schemas']['BiweeklySchedule']
          | components['schemas']['FreeFormSchedule']
          | components['schemas']['ShiftSchedule']
          | components['schemas']['SingleSchedule']
          | components['schemas']['WeeklySchedule']
        )
    }
    TapOccurrenceResult: {
      /** Format: uuid */
      id: string
      authorisation: components['schemas']['TapOccurrenceAuthorisation']
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      accompaniedBy: components['schemas']['CodedDescription']
      transport: components['schemas']['CodedDescription']
      location: components['schemas']['Location']
      isCancelled: boolean
      absenceCategorisation: string
    }
    TapOccurrenceSearchResponse: {
      content: components['schemas']['TapOccurrenceResult'][]
      metadata: components['schemas']['PageMetadata']
    }
    TapAuthorisationSearchRequest: {
      prisonCode: string
      /** Format: date */
      start?: string | null
      /** Format: date */
      end?: string | null
      status: ('PENDING' | 'APPROVED' | 'PAUSED' | 'CANCELLED' | 'DENIED' | 'EXPIRED')[]
      absenceCategorisation?: components['schemas']['AbsenceCategorisationFilter'] | null
      query?: string | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    TapAuthorisationResult: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      locations: components['schemas']['Location'][]
      /** Format: int32 */
      occurrenceCount: number
      absenceCategorisation: string
    }
    TapAuthorisationSearchResponse: {
      content: components['schemas']['TapAuthorisationResult'][]
      metadata: components['schemas']['PageMetadata']
    }
    PersonTapSearchRequest: {
      /** Format: date */
      start?: string | null
      /** Format: date */
      end?: string | null
      status: (
        | 'PENDING'
        | 'SCHEDULED'
        | 'PAUSED'
        | 'IN_PROGRESS'
        | 'COMPLETED'
        | 'OVERDUE'
        | 'EXPIRED'
        | 'CANCELLED'
        | 'DENIED'
      )[]
      absenceCategorisation?: components['schemas']['AbsenceCategorisationFilter'] | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    PersonOccurrenceAuthorisation: {
      /** Format: uuid */
      id: string
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      repeat: boolean
    }
    PersonOccurrenceResult: {
      /** Format: uuid */
      id: string
      authorisation: components['schemas']['PersonOccurrenceAuthorisation']
      prison: components['schemas']['Prison']
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      accompaniedBy: components['schemas']['CodedDescription']
      transport: components['schemas']['CodedDescription']
      location: components['schemas']['Location']
      isCancelled: boolean
      absenceCategorisation: string
    }
    PersonTapSearchResponse: {
      content: components['schemas']['PersonOccurrenceResult'][]
      metadata: components['schemas']['PageMetadata']
    }
    Prison: {
      code: string
      name: string
    }
    TapOccurrence: {
      /** Format: uuid */
      id: string
      prison: components['schemas']['Prison']
      authorisation: components['schemas']['TapOccurrence.Authorisation']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      status: components['schemas']['CodedDescription']
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      accompaniedBy: components['schemas']['CodedDescription']
      transport: components['schemas']['CodedDescription']
      contactInformation?: string | null
      comments?: string | null
      /** Format: int32 */
      occurrencePosition: number
      /** Format: int32 */
      totalOccurrences: number
      movements: components['schemas']['TapOccurrence.Movement'][]
    }
    'TapOccurrence.Authorisation': {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      status: components['schemas']['CodedDescription']
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      accompaniedBy: components['schemas']['CodedDescription']
      repeat: boolean
      comments?: string | null
      schedule?:
        | components['schemas']['BiweeklySchedule']
        | components['schemas']['FreeFormSchedule']
        | components['schemas']['ShiftSchedule']
        | components['schemas']['SingleSchedule']
        | components['schemas']['WeeklySchedule']
    }
    'TapOccurrence.Movement': {
      /** Format: uuid */
      id: string
      /** Format: date-time */
      occurredAt: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      location: components['schemas']['Location']
    }
    TapMovement: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      occurrence?: components['schemas']['TapMovement.Occurrence'] | null
      /** Format: date-time */
      occurredAt: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      prison: components['schemas']['Prison']
      absenceReason: components['schemas']['CodedDescription']
      location: components['schemas']['Location']
      accompaniedBy: components['schemas']['CodedDescription']
      accompaniedByComments?: string | null
      comments?: string | null
    }
    'TapMovement.Occurrence': {
      /** Format: uuid */
      id: string
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      status: components['schemas']['CodedDescription']
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
    }
    TapAuthorisation: {
      /** Format: uuid */
      id: string
      prison: components['schemas']['Prison']
      person: components['schemas']['Person']
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      accompaniedBy: components['schemas']['CodedDescription']
      transport: components['schemas']['CodedDescription']
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      /** Format: int64 */
      totalOccurrenceCount: number
      occurrences: components['schemas']['TapAuthorisation.Occurrence'][]
      locations: components['schemas']['Location'][]
      schedule?:
        | components['schemas']['BiweeklySchedule']
        | components['schemas']['FreeFormSchedule']
        | components['schemas']['ShiftSchedule']
        | components['schemas']['SingleSchedule']
        | components['schemas']['WeeklySchedule']
      comments?: string | null
    }
    'TapAuthorisation.Occurrence': {
      /** Format: uuid */
      id: string
      status: components['schemas']['CodedDescription']
      absenceType?: components['schemas']['CodedDescription'] | null
      absenceSubType?: components['schemas']['CodedDescription'] | null
      absenceReasonCategory?: components['schemas']['CodedDescription'] | null
      absenceReason?: components['schemas']['CodedDescription'] | null
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      accompaniedBy: components['schemas']['CodedDescription']
      transport: components['schemas']['CodedDescription']
      comments?: string | null
    }
    SyncReadTapOccurrence: {
      /** Format: uuid */
      id: string
      authorisation: components['schemas']['SyncReadTapOccurrenceAuthorisation']
      statusCode: string
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      contactInformation?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
    }
    SyncReadTapOccurrenceAuthorisation: {
      /** Format: uuid */
      id: string
      personIdentifier: string
      prisonCode: string
    }
    SyncReadTapMovement: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      occurrenceId?: string | null
      personIdentifier: string
      /** Format: date-time */
      occurredAt: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      prisonCode: string
      absenceReasonCode: string
      location: components['schemas']['Location']
      accompaniedByCode: string
      accompaniedByComments?: string | null
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
    }
    SyncReadTapAuthorisation: {
      /** Format: uuid */
      id: string
      personIdentifier: string
      prisonCode: string
      statusCode: string
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      repeat: boolean
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
      comments?: string | null
      occurrences: components['schemas']['SyncReadTapAuthorisationOccurrence'][]
    }
    SyncReadTapAuthorisationOccurrence: {
      /** Format: uuid */
      id: string
      statusCode: string
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: components['schemas']['Location']
      absenceTypeCode?: string | null
      absenceSubTypeCode?: string | null
      absenceReasonCode: string
      accompaniedByCode: string
      transportCode: string
      comments?: string | null
      created: components['schemas']['SyncAtAndBy']
      updated?: components['schemas']['SyncAtAndBy'] | null
    }
    SearchScheduledMovementsRequest: {
      movementTypes: 'TEMPORARY_ABSENCE'[]
      personIdentifiers: string[]
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      includeSensitive: boolean
      includeLocation: boolean
    }
    Detail: {
      uiUrl: string
      requiredRoles: string[]
    }
    ScheduledMovement: {
      /** Format: uuid */
      id: string
      personIdentifier: string
      domain: components['schemas']['CodedDescription']
      type: components['schemas']['CodedDescription']
      description: string
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location: string
      status: components['schemas']['CodedDescription']
      detail: components['schemas']['Detail']
    }
    ScheduledMovements: {
      content: components['schemas']['ScheduledMovement'][]
    }
    ReferenceDataResponse: {
      domain: components['schemas']['CodedDescription']
      items: components['schemas']['CodedDescription'][]
    }
    MovementInOutCount: {
      /** Format: int32 */
      outCount: number
      /** Format: int32 */
      inCount: number
    }
    PersonAuthorisationCount: {
      /** Format: int32 */
      count: number
    }
    PersonMovementsCount: {
      scheduled: components['schemas']['MovementInOutCount']
      unscheduled: components['schemas']['MovementInOutCount']
    }
    PersonOccurrenceCount: {
      /** Format: int32 */
      count: number
    }
    PersonTapCounts: {
      authorisations: components['schemas']['PersonAuthorisationCount']
      occurrences: components['schemas']['PersonOccurrenceCount']
      movements: components['schemas']['PersonMovementsCount']
    }
    PersonTapDetail: {
      scheduledAbsences: components['schemas']['ReconciliationAuthorisation'][]
      unscheduledMovements: components['schemas']['ReconciliationMovement'][]
    }
    ReconciliationAuthorisation: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      statusCode: 'PENDING' | 'APPROVED' | 'PAUSED' | 'CANCELLED' | 'DENIED' | 'EXPIRED'
      prisonCode: string
      occurrences: components['schemas']['ReconciliationOccurrence'][]
    }
    ReconciliationMovement: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      direction: 'IN' | 'OUT'
      directionPrisonCode: string
    }
    ReconciliationOccurrence: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      statusCode:
        | 'PENDING'
        | 'SCHEDULED'
        | 'PAUSED'
        | 'IN_PROGRESS'
        | 'COMPLETED'
        | 'OVERDUE'
        | 'EXPIRED'
        | 'CANCELLED'
        | 'DENIED'
      prisonCode: string
      reasonCode: string
      /** Format: date-time */
      start: string
      /** Format: date-time */
      end: string
      location?: components['schemas']['Location'] | null
      movements: components['schemas']['ReconciliationMovement'][]
    }
    Configuration: {
      tapEnabled: boolean
      courtMovementsEnabled: boolean
      transfersEnabled: boolean
      releasesEnabled: boolean
    }
    PrisonExternalMovementOverview: {
      configuration: components['schemas']['Configuration']
      tapOverview: components['schemas']['TapOverview']
    }
    TapOverview: {
      /** Format: int32 */
      leavingToday: number
      /** Format: int32 */
      returningToday: number
      /** Format: int32 */
      approvalsRequired: number
    }
    AbsenceCategorisation: {
      code: string
      description: string
      hintText?: string | null
      /** @enum {string|null} */
      nextDomain?:
        | 'ABSENCE_TYPE'
        | 'ABSENCE_SUB_TYPE'
        | 'ABSENCE_REASON_CATEGORY'
        | 'ABSENCE_REASON'
        | 'ACCOMPANIED_BY'
        | 'TRANSPORT'
        | 'TAP_AUTHORISATION_STATUS'
        | 'TAP_OCCURRENCE_STATUS'
        | null
    }
    AbsenceCategorisations: {
      domain: components['schemas']['CodedDescription']
      items: components['schemas']['AbsenceCategorisation'][]
    }
    AbsenceCategorisationFilters: {
      types: components['schemas']['Option'][]
      subTypes: components['schemas']['Option'][]
      reasons: components['schemas']['Option'][]
      workTypes: components['schemas']['Option'][]
    }
    Option: {
      /** @enum {string} */
      domainCode:
        | 'ABSENCE_TYPE'
        | 'ABSENCE_SUB_TYPE'
        | 'ABSENCE_REASON_CATEGORY'
        | 'ABSENCE_REASON'
        | 'ACCOMPANIED_BY'
        | 'TRANSPORT'
        | 'TAP_AUTHORISATION_STATUS'
        | 'TAP_OCCURRENCE_STATUS'
      code: string
      description: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getTapOccurrence: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TapOccurrence']
        }
      }
    }
  }
  applyActions: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['CancelOccurrence']
          | components['schemas']['ChangeOccurrenceAccompaniment']
          | components['schemas']['ChangeOccurrenceComments']
          | components['schemas']['ChangeOccurrenceContactInformation']
          | components['schemas']['ChangeOccurrenceLocation']
          | components['schemas']['ChangeOccurrenceTransport']
          | components['schemas']['CommenceOccurrence']
          | components['schemas']['CompleteOccurrence']
          | components['schemas']['DenyOccurrence']
          | components['schemas']['ExpireOccurrence']
          | components['schemas']['MarkOccurrenceOverdue']
          | components['schemas']['PauseOccurrence']
          | components['schemas']['RecategoriseOccurrence']
          | components['schemas']['RescheduleOccurrence']
          | components['schemas']['ResumeOccurrence']
          | components['schemas']['ScheduleOccurrence']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  getTapAuthorisation: {
    parameters: {
      query?: {
        start?: string
        end?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TapAuthorisation']
        }
      }
    }
  }
  applyActions_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ApproveAuthorisation']
          | components['schemas']['CancelAuthorisation']
          | components['schemas']['ChangeAuthorisationAccompaniment']
          | components['schemas']['ChangeAuthorisationComments']
          | components['schemas']['ChangeAuthorisationDateRange']
          | components['schemas']['ChangeAuthorisationLocation']
          | components['schemas']['ChangeAuthorisationLocations']
          | components['schemas']['ChangeAuthorisationTransport']
          | components['schemas']['ChangePrisonPerson']
          | components['schemas']['ClearAuthorisationSchedule']
          | components['schemas']['DeferAuthorisation']
          | components['schemas']['DenyAuthorisation']
          | components['schemas']['ExpireAuthorisation']
          | components['schemas']['PauseAuthorisation']
          | components['schemas']['RecategoriseAuthorisation']
          | components['schemas']['ResumeAuthorisation']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  syncTemporaryAbsenceMovement: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncWriteTapMovement']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncResponse']
        }
      }
    }
  }
  syncTemporaryAbsenceAuthorisation: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncWriteTapAuthorisation']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncResponse']
        }
      }
    }
  }
  syncTemporaryAbsenceOccurrence: {
    parameters: {
      query?: never
      header?: never
      path: {
        authorisationId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncWriteTapOccurrence']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncResponse']
        }
      }
    }
  }
  mergeTemporaryAbsences: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MigrateTapRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MigrateTapResponse']
        }
      }
    }
  }
  moveTemporaryAbsences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MoveTemporaryAbsencesRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  createTapAuthorisation: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTapAuthorisationRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceId']
        }
      }
    }
  }
  createOccurrence: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOccurrenceRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceId']
        }
      }
    }
  }
  searchTapOccurrences: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TapOccurrenceSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TapOccurrenceSearchResponse']
        }
      }
    }
  }
  searchTapAuthorisations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TapAuthorisationSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TapAuthorisationSearchResponse']
        }
      }
    }
  }
  searchPersonTap: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonTapSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PersonTapSearchResponse']
        }
      }
    }
  }
  getTapOccurrenceHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  getTapMovement: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TapMovement']
        }
      }
    }
  }
  getTapMovementHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  getTapAuthorisationHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  findTapOccurrenceById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncReadTapOccurrence']
        }
      }
    }
  }
  deleteTapOccurrenceById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  findTapMovementById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncReadTapMovement']
        }
      }
    }
  }
  deleteTapMovementById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  findTapAuthorisationById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SyncReadTapAuthorisation']
        }
      }
    }
  }
  deleteTapAuthorisationById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  externalMovementSchedules: {
    parameters: {
      query: {
        request: components['schemas']['SearchScheduledMovementsRequest']
      }
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ScheduledMovements']
        }
      }
    }
  }
  getDomain: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The reference data domain required. This is case insensitive. */
        domain:
          | 'absence-reason'
          | 'absence-reason-category'
          | 'absence-sub-type'
          | 'absence-type'
          | 'accompanied-by'
          | 'tap-authorisation-status'
          | 'tap-occurrence-status'
          | 'transport'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceDataResponse']
        }
      }
    }
  }
  countTemporaryAbsences: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PersonTapCounts']
        }
      }
    }
  }
  getTemporaryAbsences: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PersonTapDetail']
        }
      }
    }
  }
  getPrisonOverview: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonExternalMovementOverview']
        }
      }
    }
  }
  getAbsenceCategorisationDomain: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The reference data domain required. This is case insensitive. */
        domain: 'absence-reason' | 'absence-reason-category' | 'absence-sub-type' | 'absence-type'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AbsenceCategorisations']
        }
      }
    }
  }
  getAbsenceCategorisationOptions: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The reference data domain required. This is case insensitive. */
        domain: 'absence-reason' | 'absence-reason-category' | 'absence-sub-type' | 'absence-type'
        code: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AbsenceCategorisations']
        }
      }
    }
  }
  getAbsenceCategorisationFilters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AbsenceCategorisationFilters']
        }
      }
    }
  }
}
type WithRequired<T, K extends keyof T> = T & {
  [P in K]-?: T[P]
}
